server:
    port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 
        url: 
        username: 
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        show-sql: true
    servlet:
        multipart:
            maxFileSize: -1
    mail:
        host: smtp.gmail.com
        port: 587
        username: 
        password: 
app:
    upload:
        dir: ${user.dir}/resource/img/upload
        default: ${user.dir}/resource/img/upload/product/avatar/conan.png




